name : output info
on : workflow_dispatch
jobs:
    info:
        runs-on : ubuntu-latest
        steps: 
            - name : Output GitHub content
              run : echo "${{ toJSON(github) }}"
        